spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      connection-timeout: 60000

  data:
    mongodb:
      uri: ENC(BoHKYlDnL9o0Vv/sb6Kn1KI0+eclffeWXvh3dB0v/NHhEAh46KydF4UBP/vU1Y2CuzaLkzMBz6ktjcFhzs3GC5Sv4LJhj/jMvqCdoAEgHWvC0XgAqqdeUmNqS7V5MEniGVEtp2enEoM=)
      auto-index-creation: true