spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      uri: ENC(51jeryR5B+N1EuAyH58DjDhs271T71dq18ySle4M4NuB1PA29MatU1ZO/7EtyLLMq5wMcPOVrfnUSAHmOvwXmcuwKFQs5tZRuvB8Vj1Z3gKqT6NNV4HMrBrcNTtx5PXWQurAXIlw/5M=)
      auto-index-creation=true: